- src/main/java/com/kr/matitting/aop/LogAop.java
> 초기 환경 설정 수정

- build.gradle
- src/main/java/com/kr/matitting/controller/LoginController.java
- src/main/java/com/kr/matitting/dto/KakaoDto.java
- src/main/java/com/kr/matitting/entity/MsgEntity.java
- src/main/java/com/kr/matitting/repository/MemberRepository.java
- src/main/java/com/kr/matitting/service/LoginService.java
- src/main/resources/application-dev.yml
- src/main/resources/templates/index.html
카카오 로그인 Controller 구현
사용자 정보를 가져오는 Service 구현
> Feat: Kakao 로그인 구현

- build.gradle
- src/main/java/com/kr/matitting/config/QuerydslConfig.java
- src/main/java/com/kr/matitting/config/SwaggerConfig.java
- src/main/java/com/kr/matitting/constant/PartyStatus.java
- src/main/java/com/kr/matitting/constant/Role.java
- src/main/java/com/kr/matitting/constant/SocialType.java
- src/main/java/com/kr/matitting/controller/OAuthController.java
- src/main/java/com/kr/matitting/controller/PartyController.java
- src/main/java/com/kr/matitting/dto/PartySearchCondDto.java
- src/main/java/com/kr/matitting/entity/Party.java
- src/main/java/com/kr/matitting/entity/User.java
- src/main/java/com/kr/matitting/jwt/service/JwtService.java
- src/main/java/com/kr/matitting/oauth2/OAuthAttributes.java
- src/main/java/com/kr/matitting/oauth2/handler/OAuth2LoginSuccessHandler.java
- src/main/java/com/kr/matitting/oauth2/service/CustomOAuth2UserService.java
- src/main/java/com/kr/matitting/repository/PartyRepositoryCustom.java
- src/main/java/com/kr/matitting/repository/PartyRepositoryCustomImpl.java
- src/main/java/com/kr/matitting/repository/UserRepository.java
- src/main/java/com/kr/matitting/security/SecurityConfig.java
- src/main/java/com/kr/matitting/service/PartyService.java
Filter : 제목(포함), 메뉴(포함), 모집 상태(일치)
Order : 조회순, 최신순, 마감순
> Feat: 파티 참가방 검색 기능 추가

- build.gradle
- src/main/java/com/kr/matitting/MatittingApplication.java
- src/main/java/com/kr/matitting/config/RedisConfig.java
- src/main/java/com/kr/matitting/controller/SearchController.java
- src/main/java/com/kr/matitting/dto/ResponseRankingDto.java
- src/main/java/com/kr/matitting/service/PartyService.java
- src/main/java/com/kr/matitting/service/SearchService.java
검색 시 Redis Sorted Set에 keyword : score+1 기능이 실행되며
인기 검색어를 Get할 때 자동정렬되어진 Sorted Set에서 Top10을 불러오는 작업
> Feat: 인기 검색어 TOP10 구현

- src/main/java/com/kr/matitting/constant/PartyJoinStatus.java
- src/main/java/com/kr/matitting/constant/Role.java
- src/main/java/com/kr/matitting/controller/PartyController.java
- src/main/java/com/kr/matitting/dto/PartyJoinDto.java
- src/main/java/com/kr/matitting/entity/Party.java
- src/main/java/com/kr/matitting/entity/PartyJoin.java
- src/main/java/com/kr/matitting/entity/Team.java
- src/main/java/com/kr/matitting/entity/User.java
- src/main/java/com/kr/matitting/jwt/filter/JwtAuthenticationFilter.java
- src/main/java/com/kr/matitting/repository/PartyJoinRepository.java
- src/main/java/com/kr/matitting/repository/PartyRepository.java
- src/main/java/com/kr/matitting/repository/PartyTeamRepository.java
- src/main/java/com/kr/matitting/service/PartyService.java
- src/test/java/com/kr/matitting/service/PartyServiceTest.java
파티방 참가 요청 기능, 파티방 참가 수락/거절 기능 추가 구현
> Feat: 파티방 참가 기능 추가

- src/main/java/com/kr/matitting/controller/SearchController.java
- src/main/java/com/kr/matitting/dto/PartySearchCondDto.java
- src/main/java/com/kr/matitting/repository/PartyRepositoryCustomImpl.java
- src/test/java/com/kr/matitting/service/PartyServiceTest.java
- src/test/java/com/kr/matitting/service/SearchServiceTest.java
Search Sort 값이 제대로 들어가지 않아 Controller & Repository 코드 수정
> Fix: 파티방 검색 정렬 수정 및 테스트 코드 작성

- build.gradle
- src/main/java/com/kr/matitting/controller/PartyController.java
- src/main/java/com/kr/matitting/dto/PartyCreateDto.java
- src/main/java/com/kr/matitting/s3/S3Config.java
- src/main/java/com/kr/matitting/s3/S3Uploader.java
- src/main/java/com/kr/matitting/service/PartyService.java
- src/main/resources/application-dev.yml
이미지를 s3에 업로드 후 url로 변환하여 저장하는 기능 구현
> Feat: 이미지 업로드 기능 구현

- src/main/java/com/kr/matitting/controller/PartyController.java
- src/main/java/com/kr/matitting/s3/S3Uploader.java
- src/main/java/com/kr/matitting/service/PartyService.java
파티생성 API - response 값 partyId 추가
Map<K, E>으로 response 값 리턴
> modify: 파티생성, 이미지 API response값 수정

- src/main/java/com/kr/matitting/controller/ImageController.java
- src/main/java/com/kr/matitting/controller/MainController.java
- src/main/java/com/kr/matitting/controller/PartyController.java
- src/main/java/com/kr/matitting/dto/PartyCreateDto.java
- src/main/java/com/kr/matitting/entity/Party.java
- src/main/java/com/kr/matitting/entity/User.java
- src/main/java/com/kr/matitting/exception/Image/ImageException.java
- src/main/java/com/kr/matitting/exception/Image/ImageExceptionType.java
- src/main/java/com/kr/matitting/exception/Main/MainException.java
- src/main/java/com/kr/matitting/exception/Main/MainExceptionType.java
- src/main/java/com/kr/matitting/exception/party/PartyExceptionType.java
- src/main/java/com/kr/matitting/s3/S3Uploader.java
- src/main/java/com/kr/matitting/service/MainService.java
- src/main/java/com/kr/matitting/service/PartyService.java
- src/test/java/com/kr/matitting/controller/ImageControllerTest.java
- src/test/java/com/kr/matitting/controller/MainControllerTest.java
- src/test/java/com/kr/matitting/controller/PartyControllerTest.java
- src/test/java/com/kr/matitting/service/MainServiceTest.java
- src/test/java/com/kr/matitting/service/MapServiceTest.java
- src/test/java/com/kr/matitting/service/PartyServiceTest.java
> Feat: 테스트 코드 작성, 로직 수정

- src/main/java/com/kr/matitting/controller/PartyController.java
- src/main/java/com/kr/matitting/controller/SearchController.java
- src/main/java/com/kr/matitting/dto/PartyJoinDto.java
- src/main/java/com/kr/matitting/dto/PartySearchCondDto.java
- src/main/java/com/kr/matitting/jwt/filter/JwtAuthenticationFilter.java
- src/main/java/com/kr/matitting/jwt/service/JwtService.java
- src/main/java/com/kr/matitting/service/PartyService.java
- src/test/java/com/kr/matitting/controller/PartyControllerTest.java
- src/test/java/com/kr/matitting/controller/UserControllerTest.java
- src/test/java/com/kr/matitting/service/PartyServiceTest.java
- src/test/java/com/kr/matitting/service/UserServiceTest.java
- jwt token을 SecurityContextHolder에 넣는 로직 추가
- Controller에 @AuthenticationPrincipal 어노테이션 활용
> [Fix] Controller @AuthenticationPrincipal 적용 및 jwt token 로직 수정

- src/main/java/com/kr/matitting/MatittingApplication.java
- src/main/java/com/kr/matitting/controller/PartyController.java
- src/main/java/com/kr/matitting/dto/PartyCreateDto.java
- src/main/java/com/kr/matitting/dto/ResponsePartyDto.java
- src/main/java/com/kr/matitting/entity/Party.java
- src/main/java/com/kr/matitting/entity/User.java
- src/main/java/com/kr/matitting/repository/PartyRepository.java
- src/main/java/com/kr/matitting/scheduler/PartyScheduler.java
- src/main/java/com/kr/matitting/service/PartyService.java
> feat: 코드 리팩토링(엔티티 관계 수정, 조회수 증가 로직, 파티상태 변경 스케줄링)

- src/main/java/com/kr/matitting/controller/MainController.java
- src/main/java/com/kr/matitting/dto/ResponseMainPageDto.java
- src/main/java/com/kr/matitting/dto/ResponsePageInfoDto.java
- src/main/java/com/kr/matitting/dto/ResponsePartyDto.java
- src/main/java/com/kr/matitting/entity/User.java
- src/main/java/com/kr/matitting/repository/PartyRepositoryImpl.java
- src/main/java/com/kr/matitting/service/MainService.java
> feat: 메인 페이지 페이지네이션

- src/main/java/com/kr/matitting/controller/SearchController.java
- src/main/java/com/kr/matitting/dto/ResponseSearchPageDto.java
- src/main/java/com/kr/matitting/repository/PartyRepositoryCustom.java
- src/main/java/com/kr/matitting/repository/PartyRepositoryCustomImpl.java
- src/main/java/com/kr/matitting/service/SearchService.java
- pagination -> no offset으로 변경
> [mod] Search 로직 변경

- src/main/java/com/kr/matitting/repository/PartyRepositoryCustomImpl.java
- src/main/java/com/kr/matitting/repository/PartyRepositoryImpl.java
- src/main/java/com/kr/matitting/security/SecurityConfig.java
- no offset default 값 설정
- security cors 설정 추가
> [mod] 검색 수정 및 security 설정 변경

- src/main/java/com/kr/matitting/controller/testController.java
- User 생성
- AccessToken 생성 및 반환
- RefreshToken 생성 및 반환
> [fea] 더미 데이터 구현

- src/main/java/com/kr/matitting/config/CorsConfig.java
- src/main/java/com/kr/matitting/security/SecurityConfig.java
> [fix] CORS custom 설정 변경

- src/main/java/com/kr/matitting/controller/ChatController.java
- src/main/java/com/kr/matitting/repository/ChatRepositoryCustom.java
- src/main/java/com/kr/matitting/repository/ChatRepositoryCustomImpl.java
- src/main/java/com/kr/matitting/repository/ChatRoomRepository.java
- src/main/java/com/kr/matitting/service/ChatService.java
- src/test/java/com/kr/matitting/service/ChatServiceTest.java
> edit no offest

- src/main/java/com/kr/matitting/exception/token/TokenExceptionType.java
- src/main/java/com/kr/matitting/jwt/service/JwtService.java
- src/main/java/com/kr/matitting/redis/RedisConfig.java
- src/main/java/com/kr/matitting/redis/RedisUtil.java
- jwt token verify시 Exception을 잡아주는 로직 위치 변경 (jwtAuthenticationFilter -> jwtService)
> [fix] token verify Exception 로직 수정

- src/main/java/com/kr/matitting/controller/testController.java
> [mod] 사용자 dummy data 추가 생성

- src/main/java/com/kr/matitting/dto/MainPageDto.java
- 메인페이지 dto 의 필수값 설정 & swagger 수정
> Docs: 메인페이지dto swagger 수정

- src/main/java/com/kr/matitting/constant/PartyAge.java
- src/main/java/com/kr/matitting/dto/ResponseMainPageDto.java
- src/main/java/com/kr/matitting/dto/ResponseMainPartyListDto.java
- src/main/java/com/kr/matitting/dto/ResponsePartyDto.java
- main page response dto 카테고리 정보 추가
- party detail response dto 카테고리 정보 추가
> mod: main page response, party detail response dto 수정

- src/main/java/com/kr/matitting/constant/PartyAge.java
- src/main/java/com/kr/matitting/dto/ResponseMainPageDto.java
- src/main/java/com/kr/matitting/dto/ResponseMainPartyListDto.java
- src/main/java/com/kr/matitting/dto/ResponsePartyDto.java
- main page response dto에 누락되었던 카테고리 정보 추가
> mod: main page response dto 수정, swagger 수정

- src/main/java/com/kr/matitting/constant/PartyDecision.java
- src/main/java/com/kr/matitting/constant/PartyJoinStatus.java
- src/main/java/com/kr/matitting/controller/PartyController.java
- src/main/java/com/kr/matitting/dto/InvitationRequestDto.java
- src/main/java/com/kr/matitting/dto/PartyDecisionDto.java
- src/main/java/com/kr/matitting/dto/PartyJoinDto.java
- src/main/java/com/kr/matitting/dto/ResponsePartyDetailDto.java
- src/main/java/com/kr/matitting/jwt/filter/JwtAuthenticationFilter.java
- src/main/java/com/kr/matitting/repository/PartyJoinRepository.java
- src/main/java/com/kr/matitting/repository/UserRepository.java
- src/main/java/com/kr/matitting/security/SecurityConfig.java
- src/main/java/com/kr/matitting/service/PartyService.java
- src/main/java/com/kr/matitting/service/UserService.java
Commit 메세지는 develop의 FE 요청사항 수정과 같음
> [mod] FE 요청사항 수정

- src/main/java/com/kr/matitting/dto/PartyCreateDto.java
- src/main/java/com/kr/matitting/repository/PartyRepositoryImpl.java
- 파티 생성 시 menu 값을 필수값으로 수정
- 메인페이지 조회 쿼리 중 누락된 'size+1' 조건 추가
> mod: 파티 생성 dto 필수값 추가, 메인페이지 조회 시 pageable size 확인 추가

- src/main/java/com/kr/matitting/controller/SearchController.java
- src/main/java/com/kr/matitting/dto/ResponseRankingDto.java
- 한글이 깨지지 않게 하기 위해서 json 형식으로 data를 return하려고 하니 [No serializer found for class] error를 직면하여 해결
> [fix] ResponseRankingDto 수정

- src/main/java/com/kr/matitting/service/PartyService.java
- Party Join CANCEL시 삭제가 되지 않는 이슈 수정
> 파티 신청 CANCEL 로직 수정

- src/main/java/com/kr/matitting/service/PartyService.java
> 파티 신청 취소 로직 수정

- src/main/java/com/kr/matitting/constant/Gender.java
- src/main/java/com/kr/matitting/controller/OAuthController.java
- src/main/java/com/kr/matitting/controller/PartyController.java
- src/main/java/com/kr/matitting/controller/SearchController.java
- src/main/java/com/kr/matitting/controller/UserController.java
- src/main/java/com/kr/matitting/dto/ResponseUserDto.java
- src/main/java/com/kr/matitting/dto/UserLoginDto.java
- src/main/java/com/kr/matitting/entity/ChatRoom.java
- src/main/java/com/kr/matitting/entity/Party.java
- src/main/java/com/kr/matitting/exception/user/UserExceptionType.java
- src/main/java/com/kr/matitting/jwt/service/JwtService.java
- src/main/java/com/kr/matitting/oauth2/handler/OAuth2LoginSuccessHandler.java
- src/main/java/com/kr/matitting/service/UserService.java
- 내 프로필 정보 기능 개발
- Swagger 상세 설명 추가
- 로그인 시 front로 userId와 role, token 값만 던지도록 로직 수정
- Party를 삭제할 때, ChatRoom과 양방향 매핑이 안되어 있어 Cascade 부분에서 error 발생
- ChatRoom을 삭제할 때 양방향 매핑이 안되어 있어 Cascade 부분에서 error 발생
> 요청사항 로직 수정 및 Swagger 상세 설명 추가

- src/main/java/com/kr/matitting/controller/ImageController.java
- src/main/java/com/kr/matitting/controller/MainController.java
- src/main/java/com/kr/matitting/controller/PartyController.java
- src/main/java/com/kr/matitting/dto/PartyCreateDto.java
- src/main/java/com/kr/matitting/service/PartyService.java
- title -> partyTitle
- content -> partyContent
> mod: swagger description 수정 및 party create dto parameter 수정

- src/main/java/com/kr/matitting/dto/PartyUpdateDto.java
- src/main/java/com/kr/matitting/dto/ResponsePartyDetailDto.java
- src/main/java/com/kr/matitting/dto/ResponsePartyDto.java
- src/main/java/com/kr/matitting/service/PartyService.java
- PartyUpdateDto에 컬럼 추가
- ResponsePartyDetailDto에 컬럼추가
- ResponsePartyDto에 컬럼 추가
- PartyService 로직 수정
> 파티 위치 Column 추가 및 로직 수정

- src/main/java/com/kr/matitting/controller/OAuthController.java
- src/main/java/com/kr/matitting/controller/UserController.java
- src/main/java/com/kr/matitting/controller/testController.java
- src/main/java/com/kr/matitting/jwt/filter/JwtAuthenticationFilter.java
- src/main/java/com/kr/matitting/oauth2/dto/KakaoParams.java
- src/main/java/com/kr/matitting/oauth2/dto/NaverParams.java
- src/main/java/com/kr/matitting/security/SecurityConfig.java
- src/main/java/com/kr/matitting/service/PartyService.java
- src/main/java/com/kr/matitting/service/UserService.java
> 01.28 정기회의 수정 요청 사항 처리

- src/main/java/com/kr/matitting/security/SecurityConfig.java
- src/main/java/com/kr/matitting/service/UserService.java
- config.setExposedHeaders 설정에서 List.of("*")로 모든 Header에 대해서 접근 권한 해제를 해주었다고 생각하였지만, Authorization 등처럼 직접적인 명시를 해줘야 접근 권한이 해제되는 것으로 판별 🐛
> Access-Control-Expose-Headers & CORS-safelisted response header 이슈 해결

- src/main/java/com/kr/matitting/controller/testController.java
누락된 임시 유저 생성 API 파일 testController 추가하였습니다.
> Fix: 임시 유저 생성 API 누락파일 업로드

- src/main/java/com/kr/matitting/exception/Main/MainExceptionType.java
- src/main/java/com/kr/matitting/exception/chat/ChatExceptionType.java
- src/main/java/com/kr/matitting/exception/party/PartyExceptionType.java
> Feat: exception http status 수정

- src/main/java/com/kr/matitting/jwt/service/JwtService.java
- src/main/java/com/kr/matitting/oauth2/service/OauthService.java
- refreshToken 발급과 등록을 따로 진행했으나 발급과 동시에 등록을 진행하도록 수정 🐞
> refreshToken 등록 로직 수정

- src/main/java/com/kr/matitting/controller/NotificationController.java
- src/main/java/com/kr/matitting/controller/OAuthController.java
- src/main/java/com/kr/matitting/controller/PartyController.java
- src/main/java/com/kr/matitting/controller/SearchController.java
- src/main/java/com/kr/matitting/controller/UserController.java
- src/main/java/com/kr/matitting/exception/token/TokenExceptionType.java
- src/main/java/com/kr/matitting/jwt/service/JwtService.java
- src/main/java/com/kr/matitting/oauth2/client/KakaoClient.java
- src/main/java/com/kr/matitting/oauth2/client/NaverClient.java
- Front에서 Swagger에 있는 responseCode가 헷갈려 수정해달라는 요청이 들어왔다. 그에 따라서 responseCode를 StatusCode가 아닌 내부 errorCode로 대체하기로 마음먹었고 StatusCode와 중복되는 것은 삭제 및 수정하였으며, 로직에 추가된 Exception은 Swagger에 추가하였다 💯
> Swagger에 Exception 수정

- src/main/java/com/kr/matitting/oauth2/service/OauthService.java
- 소셜 로그인 시 회원가입을 진행하지 않고 재 로그인 시 GUEST의 정보가 남아 있어서 GUEST Role로 Token을 생성하려고 하다가 403에러가 발생하는 이슈가 발생하였다. 그래서 로그인 시 DB에 값이 있는 경우 Role을 검사해 GUEST면 해당 정보를 지우고 재등록 하며, 신규 유저로 인식하도록 로직을 수정하였다. 👶
> 소셜 로그인 로직 수정

- src/main/java/com/kr/matitting/constant/ReviewType.java
- src/main/java/com/kr/matitting/controller/OAuthController.java
- src/main/java/com/kr/matitting/controller/ReviewController.java
- src/main/java/com/kr/matitting/dto/ReviewCreateReq.java
- src/main/java/com/kr/matitting/dto/ReviewCreateRes.java
- src/main/java/com/kr/matitting/dto/ReviewDeleteReq.java
- src/main/java/com/kr/matitting/dto/ReviewGetRes.java
- src/main/java/com/kr/matitting/dto/ReviewInfoRes.java
- src/main/java/com/kr/matitting/dto/ReviewUpdateReq.java
- src/main/java/com/kr/matitting/entity/Party.java
- src/main/java/com/kr/matitting/entity/Review.java
- src/main/java/com/kr/matitting/entity/User.java
- src/main/java/com/kr/matitting/exception/reivew/ReviewException.java
- src/main/java/com/kr/matitting/exception/reivew/ReviewExceptionType.java
- src/main/java/com/kr/matitting/oauth2/service/OauthService.java
- src/main/java/com/kr/matitting/repository/ReviewRepository.java
- src/main/java/com/kr/matitting/scheduler/PartyScheduler.java
- src/main/java/com/kr/matitting/service/ReviewService.java
- src/main/java/com/kr/matitting/service/UserService.java
- src/test/java/com/kr/matitting/service/ReviewServiceTest.java
- 리뷰 생성 : 리뷰 내용, 온도, 리뷰 속성들을 고려하여 리뷰 작성이 가능하도록 구현 💞 
- 리뷰 리스트 조회 : ReviewType을 입력받아 내가 보낸 리뷰 or 내가 받은 리뷰 리스트를 반환하도록 구현 🥇 
- 리뷰 상세조회 : 리뷰 리스트 response에 있는 reviewId를 request로 받아서 리뷰의 상세 내용 + 리뷰를 쓴 사람인지의 유무를 Response하여 수정 버튼을 만드는데 용이하도록 설계 및 개발 완료 🚒 
- 리뷰 수정&삭제 : 리뷰 수정과 삭제를 진행할 때 해당 로직을 요청하는 사용자가 쓴 리뷰인지 check후 수정 및 삭제 🦖 
- 테스트 코드 구현 완료 🧪 
- 아직 리뷰에 대한 로직을 혼자 생각하여 이처럼 구현하였다. 리뷰에 온도 기능을 넣은것은 맛있팅 피그마 사이트를 보았으며 이는 확정이 아니기에 User Entity에 Rating Column을 추가하진 않았다. 2024.03.24 회의에 리뷰에 대한 기능을 정의 및 설계하고 확정 시 추후에 수정할 예정 🌱
> 리뷰 기능 구현 완료

- src/main/java/com/kr/matitting/controller/SearchController.java
- src/main/java/com/kr/matitting/dto/ResponseSearchPageDto.java
- src/main/java/com/kr/matitting/service/PartyService.java
- src/main/java/com/kr/matitting/service/SearchService.java
- src/test/java/com/kr/matitting/service/SearchServiceTest.java
- 파티 검색결과 Response시에 hasNext, page 값을 추가로 return 🐐 
- 테스트 코드 수정 🧪
> 파티 검색 로직 추가

- src/main/java/com/kr/matitting/controller/testController.java
- src/main/java/com/kr/matitting/dto/ResponsePageDto.java
- src/main/java/com/kr/matitting/dto/ResponseSearchPageDto.java
- src/main/java/com/kr/matitting/repository/PartyRepositoryCustom.java
- src/main/java/com/kr/matitting/repository/PartyRepositoryCustomImpl.java
- src/main/java/com/kr/matitting/service/SearchService.java
- src/test/java/com/kr/matitting/service/SearchServiceTest.java
- 파티 검색 시 Response가 partyList, page, hasNext로 구성되어 있었지만 Main 쪽 Response와 맞추기 위해서 partyList와 pageInfo(page, hasNext)로 구성 변경 🐤
> 검색 Response 수정

- src/main/java/com/kr/matitting/ProductInitializer.java
- src/main/java/com/kr/matitting/dto/PartyCreateDto.java
- src/main/java/com/kr/matitting/entity/ChatRoom.java
- src/main/java/com/kr/matitting/entity/ChatUser.java
- src/main/java/com/kr/matitting/service/ChatService.java
- src/main/java/com/kr/matitting/service/PartyService.java
**수정사항**
- increaseHit() - class 단에 @Transactional 처리되어있어 삭제
- @AuthenticationPrincipal 로 User 검증하고 있기 때문에 partySevice - createParty()내 유저 검증 불필요하여 삭제
- checkParticipant(): 참여인원수 controller단에서 @Min을 사용하여 검증
- createBasePartyBuilder(): participantCount 의 default 값 1로 설정
- 채팅방 생성, 채팅방 참여 인원 추가 메서드 실행 시 필요정보 파라미터로 전달
- ChatRoom, ChatUser 엔티티 생성자 사용으로 객체 생성과 초기화
> Feat: 코드 리팩토링

- src/main/java/com/kr/matitting/dto/ResponseMyInfo.java
- src/main/java/com/kr/matitting/dto/ReviewCreateReq.java
- src/main/java/com/kr/matitting/dto/ReviewGetRes.java
- src/main/java/com/kr/matitting/dto/ReviewUpdateReq.java
- src/main/java/com/kr/matitting/entity/Review.java
- src/main/java/com/kr/matitting/entity/User.java
- src/main/java/com/kr/matitting/service/ReviewService.java
- src/main/java/com/kr/matitting/service/UserService.java
- 리뷰 이미지를 List로 변환하여 여러 장 등록할 수 있도록 수정 완료 🐛 
- 리뷰 조회 시 생성일자 추가 👍 
- 리뷰 리스트 조회 시 content 10자로 짜르던 것 취소 전체를 return 🌜 
- 내 프로필 조회 시 평균 rating column 추가 🐰 
#119 참고 부탁드려요! 🪧
> 리뷰 요청사항 수정

- src/main/java/com/kr/matitting/dto/InvitationRequestDto.java
- src/main/java/com/kr/matitting/dto/PartyJoinDto.java
- src/main/java/com/kr/matitting/entity/PartyJoin.java
- src/main/java/com/kr/matitting/service/PartyService.java
- src/test/java/com/kr/matitting/service/PartyServiceTest.java
- src/test/java/com/kr/matitting/service/ReviewServiceTest.java
- src/test/java/com/kr/matitting/service/UserServiceTest.java
- 파티 신청을 할 때 한줄 소개를 추가하여 방장이 팀원들을 고르는 기준을 추가하였다. 이를 통해서 본인 파티와 결이 더 잘 맞는 사람들을 초대하여 좋은 파티를 만들 수 있다는 생각이 들었다 🙅‍♂️
> 파티 신청 요청사항 수정

- src/main/java/com/kr/matitting/controller/ReviewController.java
- src/main/java/com/kr/matitting/dto/ResponseNoOffsetDto.java
- src/main/java/com/kr/matitting/dto/ResponseReviewList.java
- src/main/java/com/kr/matitting/dto/ReviewCreateReq.java
- src/main/java/com/kr/matitting/dto/ReviewGetRes.java
- src/main/java/com/kr/matitting/dto/ReviewUpdateReq.java
- src/main/java/com/kr/matitting/service/ReviewService.java
- src/test/java/com/kr/matitting/service/PartyServiceTest.java
- src/test/java/com/kr/matitting/service/ReviewServiceTest.java
- src/test/java/com/kr/matitting/service/UserServiceTest.java
- 저번 페이지네이션 작업을 진행할 때 누락된 리뷰 리스트 API에 페이지네이션 기능을 적용 👍
> 리뷰 리스트 조회 페이지네이션 기능 적용

- src/main/java/com/kr/matitting/controller/PartyController.java
- src/main/java/com/kr/matitting/dto/PartyStatusReq.java
- JPA에서 제공해주는 Pageable 객체를 Request 객체로 사용하고 있다보니 Swagger에 자세한 설명이 누락되었다는 요청을 받고 Swagger 보충 완료 🐛 
- Request Dto에서 누락되어 있는 Swagger 추가 완료 😭
> 파티 현황 Swagger 수정

- src/main/java/com/kr/matitting/controller/testController.java
- src/main/java/com/kr/matitting/dto/ReviewGetRes.java
- src/main/java/com/kr/matitting/dto/ReviewInfoRes.java
- Review Dto들의 Swagger example 설명을 수정 😭
> 리뷰 Swagger 보충

- src/main/java/com/kr/matitting/dto/NotificationDto.java
- src/main/java/com/kr/matitting/scheduler/PartyScheduler.java
- src/main/java/com/kr/matitting/service/NotificationService.java
- src/main/java/com/kr/matitting/service/PartyService.java
- 알림 클릭 시 라우팅 처리가 필요하여 partyId와 hostId Column 추가가 필요하다는 요청을 받아서 처리 완료 💯
> 알림 Response Column 추가

- src/main/java/com/kr/matitting/config/WebSocketConfig.java
- src/main/java/com/kr/matitting/handler/StompHandler.java
- src/main/java/com/kr/matitting/jwt/filter/JwtAuthenticationFilter.java
- src/main/java/com/kr/matitting/security/SecurityConfig.java
- 소켓 연결 앤드포인트 security 설정
- stomp handler 예외 처리
> Fix: 웹 소켓 연결
